//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainEntities.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comenzi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Comenzi()
        {
            this.DetaliuComandas = new HashSet<DetaliuComanda>();
        }
    
        public int ComandaId { get; set; }
        public string StareComanda { get; set; }
        public System.DateTime DataSystem { get; set; }
        public System.DateTime DataProgramare { get; set; }
        public System.DateTime DataFinalizare { get; set; }
        public int KmBord { get; set; }
        public string Descriere { get; set; }
        public decimal ValoarePiese { get; set; }
        public int OperatieOperatieId { get; set; }
        public int Auto_AutoId { get; set; }
        public int Client_ClientId { get; set; }
    
        public virtual Auto Auto { get; set; }
        public virtual Clienti Clienti { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetaliuComanda> DetaliuComandas { get; set; }
        public virtual Operatii Operatii { get; set; }
    }
}
